# Generated by Django 4.2.2 on 2023-07-17 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0006_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phoneno',
            field=models.IntegerField(null=True),
        ),
    ]
